// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statmath.Application.Task.Data.Context;

namespace Statmath.Application.Task.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Statmath.Application.Task.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("eb96e1f9-4d74-4ac5-9cca-f36e86000a22"));

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TIMESTAMP(0)");

                    b.Property<int>("Job")
                        .HasColumnType("integer");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(0)");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
