// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statmath.Application.Data.Context;

namespace Statmath.Application.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210415140141_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Statmath.Application.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("4dee0cc0-e106-4536-b650-0ea4e4865826"));

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TIMESTAMP(0)");

                    b.Property<int>("Job")
                        .HasColumnType("integer");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(0)");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("Job")
                        .IsUnique();

                    b.ToTable("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
